### ISSUE TITLE
TransactionDTO is missing a few Transaction Types

### ISSUE THREAD

**Issue by AsafPolakovski** [unit-finance/unit-python-sdk#100]
TransactionDTO is missing a few [Transaction Types](https://docs.unit.co/transactions#transaction-types).
What should be expected behavior for new transactions types not supported by the SDK? Should we add an UnrecognizedTransactionDTO type for backwards compatibility or maybe an empty dict? @axshani what do you think?

**Comment by axshani** [comment]
RawUnitObject to the rescue!
