### ISSUE TITLE
unexpected keyword argument 'jwtSubject' - not working

### ISSUE THREAD

**Issue by DavidCrediverso** [unit-finance/unit-python-sdk#119]
Customer:

Individual - must contain at least one: jwtSubject field or AuthorizedUser's jwtSubject field.

Business - must contain at least one: Contact's jwtSubject field or AuthorizedUser's jwtSubject field.

**Comment by axshani** [comment]
Hi,
We  added the jwtSubject field
https://github.com/unit-finance/unit-python-sdk/pull/121

Thanks
