### ISSUE TITLE
`__repr__` does not return the object

### ISSUE THREAD

**Issue by kasipavankumar** [unit-finance/unit-python-sdk#188]
In a couple of [places](https://github.com/search?q=repo%3Aunit-finance%2Funit-python-sdk%20__repr__&type=code), the `__repr__` method does not return the object.

For instance in check deposit models.

https://github.com/unit-finance/unit-python-sdk/blob/b04af2908f14b2ea85f1c0fea861e515bfb46ff0/unit/models/check_deposit.py#L58-L59

Shouldn't the method be as follows?

```py
def __repr__(self):
  return json.dumps(self.to_json_api())
```

**Comment by Yaellever** [comment]
Thanks for the input @kasipavankumar!
I added this fix to our backlog and we will get to it as soon as it is prioritized. If you prefer, you can also send a PR with this fix which will be reviewed and approved within about a week.
Yael.
