### ISSUE TITLE
`__str__` method in `UnitErrorPayload` returns None when detail is missing

### ISSUE THREAD

**Issue by kasipavankumar** [unit-finance/unit-python-sdk#189]
## Problem

The `__str__` method defined on the [`UnitErrorPayload`](https://github.com/unit-finance/unit-python-sdk/blob/b04af2908f14b2ea85f1c0fea861e515bfb46ff0/unit/models/__init__.py#L87) returns `None` in the case where `detail` is absent in the API response.

https://github.com/unit-finance/unit-python-sdk/blob/b04af2908f14b2ea85f1c0fea861e515bfb46ff0/unit/models/__init__.py#L98-L99

## Scenario

For example, following is the response when close account is called on an already closed account, which does not have detail in it; and `__str__` method would return `None`.

```json
{
  "errors": [
    {
      "title": "Account is already closed",
      "status": "400"
    }
  ]
}
```

## Proposed solution

If it can be assumed that either `title` or `detail` will be present in the response, the following can be done.

```py
def __str__(self):
  return self.title or self.detail
```

**Comment by Yaellever** [comment]
Thanks for the input @kasipavankumar!
I added this fix to our backlog and we will get to it as soon as it is prioritized. If you prefer, you can also send a PR with this fix which will be reviewed and approved within about a week.
Yael.
