### ISSUE TITLE
SSN is not type annotated on BaseCreateIndividualApplicationRequest

### ISSUE THREAD

**Issue by sai9raman** [unit-finance/unit-python-sdk#218]
https://github.com/unit-finance/unit-python-sdk/blob/cee80449cb7a6bc492cf7fe080af7e53fa398027/unit/models/application.py#LL140C70-L140C70

Looks like it should be an `Optional[str]`

**Comment by axshani** [comment]
https://github.com/unit-finance/unit-python-sdk/pull/220

thanks
