### ISSUE TITLE
Add CreditOnly to CounterpartyPermissions

### ISSUE THREAD

**Issue by sai9raman** [unit-finance/unit-python-sdk#245]
https://docs.unit.co/payments-counterparties#create-counterparty-with-plaid-token

As per the docs, the permissions field could be one of `CreditOnly`, `DebitOnly`, or `CreditAndDebit`. However the sdk only supports Literal["DebitOnly", "CreditAndDebit"] over [here](https://github.com/unit-finance/unit-python-sdk/blob/7ca6be7850c045207bf8b3d15d02ab7ba0695362/unit/models/counterparty.py#L28). 

Update this Literal to allow `CreditOnly` as well

**Comment by leahunit** [comment]
Added to Trello board
