### ISSUE TITLE
Counterparty Encoder using incorrect case

### ISSUE THREAD

**Issue by dtmeadows** [unit-finance/unit-python-sdk#65]
https://github.com/unit-finance/unit-python-sdk/blob/14c52e7648b1780307165e8c8a8786e5aa1a48a0/unit/models/codecs.py#L335-L336

These are currently in the incorrect case, I believe? Instead of `routingNumber` it should be `routing_number`.

**Comment by axshani** [comment]
Thanks for the notice
https://github.com/unit-finance/unit-python-sdk/pull/61
