### ISSUE TITLE
Documentation about contributing

### ISSUE THREAD

**Issue by robertoyoc** [unit-finance/unit-python-sdk#76]
I can't find a way to setup the project for development or run unit testing.

Could you please provide it? Thanks.

**Comment by chita13** [comment]
Hi @robertoyoc 
We will add to the readme file a command to run the tests. You can use the one that we are running in our CI (added recently) - `TOKEN=<your_token> py.test` (after installing requirements-dev) and I'm not sure what else is missing?

**Comment by robertoyoc** [comment]
Nice! thanks @chita13. That will be really helpful. Basically I want to be able to execute the tests, so having a command for that is good enough :)
